name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkshit
      run: sudo apt-get update && sudo apt-get install -y mingw-w64
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: cd build && ls -la
    - name: Upload executable
      uses: actions/upload-artifact@v4.6.2
      with:
        name: hamer-windows-exe
        path: path/to/hamer.exe
